### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by mlampros** [s-u/ghroute#1]
hi, and thanks for making this R package publicly available.

I'd like to run the functions of the [tests](https://github.com/s-u/ghroute/blob/master/tests/tests.R) but with a bigger file than the 'cyprus.pbf' which is 26.8 MB. For instance when I use a .pbf file of 296.8 MB (greece-latest.pbf) I receive 

```
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.lang.OutOfMemoryError: Java heap space - problem when allocating new memory. Old capacity: 12582912, new bytes:12, segmentSizeIntsPower:18, new segments:1, existing:12
```
which means I have to increase the java heap space

In the official [graphhopper-docker](https://github.com/IsraelHikingMap/graphhopper-docker-image-push) repository there is the option to increase the heap size by using 

JAVA_OPTS: "-Xmx1g -Xms1g"

when using the `docker run ..` command

Is there any similar argument that the user can pass to the `router()` function of the `ghroute` R package for this purpose?

thank you in advance

**Comment by s-u** [comment]
@mlampros yes, you want to set the `java.parameters` option, e.g.

```
options(java.parameters="-Xmx8g")
```

 before you run the `router` command (or before you load any other Java package - if you do that).

**Comment by mlampros** [comment]
by setting `options(java.parameters="-Xmx8g")` it works.
thank you.

**Comment by s-u** [comment]
Thanks, I have added a mention of it to the documentation.
